imports:
    - { resource: '@JoliMediaSyliusBundle/config/app.php' }

joli_media_sylius:
#    pagination:
#        per_page: [10, 25, 50]
#    visibility:
#        show_variations_list: true
#        show_variations_list_admin_variations: true
#        show_variations_stored: true
#        show_variations_action_regenerate: true
#        show_html_code: true
#        show_markdown_code: true
    upload:
        max_files: 20
        max_file_size: 500
        accepted_files:
            - audio/*
            - image/*
            - video/*

