<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260415165823 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE game_video (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, media VARCHAR(255) NOT NULL, game_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4EF4A3A3E48FD905 ON game_video (game_id)');
        $this->addSql('ALTER TABLE game_video ADD CONSTRAINT FK_4EF4A3A3E48FD905 FOREIGN KEY (game_id) REFERENCES game (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE game_video DROP CONSTRAINT FK_4EF4A3A3E48FD905');
        $this->addSql('DROP TABLE game_video');
    }
}
